/**
 * Catálogo de medios. GENERADO por src/catalogo.mjs a partir del directorio
 * editorial y de la exploración de feeds. No editar a mano: se regenera.
 *
 * 167 medios con feed verificado.
 *   Nivel A: 60  ·  B: 62  ·  C: 36  ·  D: 9
 *
 * El nivel dice cómo tratar al medio, no si publica verdad o mentira:
 *   A base de verificación · B contrastar · C versión de parte · D nunca confirmación única.
 *
 * `peso` inclina el ranking; `eje` permite ver si un hecho lo cubren partes
 * enfrentadas o todos desde el mismo lado.
 */

export const FUENTES = [
  { id: "972-magazine", medio: "+972 Magazine", url: "https://www.972mag.com/rss", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Pro derechos palestinos", pais: "ISRAEL/PALESTINA" },
  { id: "abc-news-australia", medio: "ABC News Australia", url: "https://news.google.com/rss/search?q=when:2d+site:abc.net.au&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Australia / occidental", pais: "AUSTRALIA" },
  { id: "afp", medio: "AFP", url: "https://www.afp.com/rss.xml", idioma: "fr", alcance: "global", peso: 1.3, nivel: "A", eje: "Francia / global", pais: "FRANCIA" },
  { id: "agence-france-presse-afp", medio: "Agence France-Presse (AFP)", url: "https://www.afp.com/en/news-hub/rss.xml", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeo-global", pais: "FRANCIA/INTERNACIONAL" },
  { id: "agencia-brasil", medio: "Agência Brasil", url: "https://agenciabrasil.ebc.com.br/rss.xml", idioma: "pt", alcance: "latam", peso: 1.3, nivel: "A", eje: "Brasil estatal/público", pais: "BRASIL" },
  { id: "agencia-efe", medio: "Agencia EFE", url: "https://news.google.com/rss/search?q=when:2d+site:efe.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "global", peso: 1.3, nivel: "A", eje: "Iberoamericano-europeo", pais: "ESPAÑA/INTERNACIONAL" },
  { id: "alt-news", medio: "Alt News", url: "https://www.altnews.in/feed/", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Fact-check regional", pais: "INDIA" },
  { id: "ansa", medio: "ANSA", url: "https://news.google.com/rss/search?q=when:2d+site:ansa.it&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "it", alcance: "global", peso: 1.3, nivel: "A", eje: "Italia / UE", pais: "ITALIA" },
  { id: "aos-fatos", medio: "Aos Fatos", url: "https://www.aosfatos.org/noticias/feed/", idioma: "pt", alcance: "latam", peso: 1.3, nivel: "A", eje: "Fact-check", pais: "BRASIL" },
  { id: "associated-press-ap", medio: "Associated Press (AP)", url: "https://news.google.com/rss/search?q=when:2d+site:apnews.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Occidental-global", pais: "INTERNACIONAL" },
  { id: "bbc-news", medio: "BBC News", url: "https://www.bbc.com/news/rss.xml", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Atlántico / Reino Unido", pais: "REINO UNIDO" },
  { id: "cambio", medio: "Cambio", url: "https://cambiocolombia.com/feeds/articulos/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Colombia plural", pais: "COLOMBIA" },
  { id: "cazadores-de-fake-news", medio: "Cazadores de Fake News", url: "https://cazadores.info/feed/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Fact-check", pais: "VENEZUELA" },
  { id: "chequeado", medio: "Chequeado", url: "https://chequeado.com/feed/?post_type=nota", idioma: "es", alcance: "ar", peso: 1.3, nivel: "A", eje: "Fact-check", pais: "ARGENTINA" },
  { id: "ciper", medio: "CIPER", url: "https://www.ciperchile.cl/feed/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Chile pluralista", pais: "CHILE" },
  { id: "colombiacheck", medio: "ColombiaCheck", url: "https://colombiacheck.com/rss.xml", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Fact-check", pais: "COLOMBIA" },
  { id: "confidencial", medio: "Confidencial", url: "https://confidencial.digital/rss", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Anti-autoritarismo", pais: "NICARAGUA/EXILIO" },
  { id: "daily-maverick", medio: "Daily Maverick", url: "https://www.dailymaverick.co.za/rss", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Sudáfrica pluralista", pais: "SUDÁFRICA" },
  { id: "dawn", medio: "Dawn", url: "https://www.dawn.com/feeds/home/", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Pakistán civil", pais: "PAKISTÁN" },
  { id: "der-spiegel", medio: "Der Spiegel", url: "https://www.spiegel.de/schlagzeilen/index.rss", idioma: "de", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta", pais: "ALEMANIA" },
  { id: "deutsche-welle", medio: "Deutsche Welle", url: "https://news.google.com/rss/search?q=when:2d+site:dw.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "de", alcance: "global", peso: 1.3, nivel: "A", eje: "Alemania / UE / atlántico", pais: "ALEMANIA" },
  { id: "efecto-cocuyo", medio: "Efecto Cocuyo", url: "https://efectococuyo.com/rss", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Venezuela pluralista", pais: "VENEZUELA" },
  { id: "el-espectador", medio: "El Espectador", url: "https://www.elespectador.com/arc/outboundfeeds/discover/?outputType=xml", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Colombia liberal", pais: "COLOMBIA" },
  { id: "el-mundo", medio: "El Mundo", url: "https://www.elmundo.es/rss/googlenews/portada.xml", idioma: "es", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta-conservador", pais: "ESPAÑA" },
  { id: "el-pais", medio: "El País", url: "https://news.google.com/rss/search?q=when:2d+site:elpais.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta / atlántico", pais: "ESPAÑA" },
  { id: "el-pais-uruguay", medio: "El País Uruguay", url: "https://www.elpais.com.uy/rss", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Uruguay liberal-conservador", pais: "URUGUAY" },
  { id: "el-pitazo", medio: "El Pitazo", url: "https://elpitazo.net/feed/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Venezuela pluralista", pais: "VENEZUELA" },
  { id: "eldiario-es", medio: "elDiario.es", url: "https://www.eldiario.es/rss/", idioma: "es", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta progresista", pais: "ESPAÑA" },
  { id: "euobserver", medio: "EUobserver", url: "https://euobserver.com/feed/", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta crítico", pais: "UNIÓN EUROPEA" },
  { id: "financial-times", medio: "Financial Times", url: "https://www.ft.com/rss/", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Atlántico-global / negocios", pais: "REINO UNIDO" },
  { id: "france-24", medio: "France 24", url: "https://www.france24.com/en/rss", idioma: "fr", alcance: "global", peso: 1.3, nivel: "A", eje: "Proyección francesa/europea", pais: "FRANCIA" },
  { id: "frankfurter-allgemeine-faz", medio: "Frankfurter Allgemeine (FAZ)", url: "https://www.faz.net/rss/aktuell/", idioma: "de", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta / mercado", pais: "ALEMANIA" },
  { id: "gk", medio: "GK", url: "https://gk.city/feed/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Ecuador pluralista", pais: "ECUADOR" },
  { id: "inkyfada", medio: "Inkyfada", url: "https://inkyfada.com/en/feed/", idioma: "ar", alcance: "global", peso: 1.3, nivel: "A", eje: "Túnez pluralista", pais: "TÚNEZ" },
  { id: "la-diaria", medio: "la diaria", url: "https://ladiaria.com.uy/feeds/articulos/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Uruguay progresista", pais: "URUGUAY" },
  { id: "la-nacion", medio: "La Nación", url: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/", idioma: "es", alcance: "ar", peso: 1.3, nivel: "A", eje: "Prooccidental / mercado", pais: "ARGENTINA" },
  { id: "la-silla-vacia", medio: "La Silla Vacía", url: "https://www.lasillavacia.com/feed/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Colombia plural", pais: "COLOMBIA" },
  { id: "la-tercera", medio: "La Tercera", url: "https://www.latercera.com/rss", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Prooccidental / mercado", pais: "CHILE" },
  { id: "la-vanguardia", medio: "La Vanguardia", url: "https://www.lavanguardia.com/rss/home.xml", idioma: "es", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta", pais: "ESPAÑA" },
  { id: "le-monde", medio: "Le Monde", url: "https://www.lemonde.fr/en/rss/une.xml", idioma: "fr", alcance: "global", peso: 1.3, nivel: "A", eje: "Europeísta", pais: "FRANCIA" },
  { id: "mada-masr", medio: "Mada Masr", url: "https://www.madamasr.com/en/rss", idioma: "ar", alcance: "global", peso: 1.3, nivel: "A", eje: "Egipto pluralista", pais: "EGIPTO" },
  { id: "mail-guardian", medio: "Mail & Guardian", url: "https://mg.co.za/atom/", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Panafricano progresista", pais: "SUDÁFRICA" },
  { id: "nhk-world-japan", medio: "NHK World-Japan", url: "https://news.google.com/rss/search?q=when:2d+site:www3.nhk.or.jp&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "ja", alcance: "global", peso: 1.3, nivel: "A", eje: "Japón / aliado occidental", pais: "JAPÓN" },
  { id: "nikkei-asia", medio: "Nikkei Asia", url: "https://news.google.com/rss/search?q=when:2d+site:asia.nikkei.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Asia-Pacífico / negocios", pais: "JAPÓN" },
  { id: "npr", medio: "NPR", url: "https://feeds.npr.org/1002/rss.xml", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Occidental / servicio público", pais: "ESTADOS UNIDOS" },
  { id: "o-estado-de-s-paulo", medio: "O Estado de S. Paulo", url: "https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/geral/?body=%7B%22layout%22:%22google-news%22%7D", idioma: "pt", alcance: "latam", peso: 1.3, nivel: "A", eje: "Promercado", pais: "BRASIL" },
  { id: "pbs-newshour", medio: "PBS NewsHour", url: "https://www.pbs.org/newshour/feeds/rss/headlines", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Servicio público estadounidense", pais: "ESTADOS UNIDOS" },
  { id: "pie-de-pagina", medio: "Pie de Página", url: "https://piedepagina.mx/feed/", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "México pluralista", pais: "MÉXICO" },
  { id: "premium-times", medio: "Premium Times", url: "https://www.premiumtimesng.com/feed", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Nigeria pluralista", pais: "NIGERIA" },
  { id: "propublica", medio: "ProPublica", url: "https://www.propublica.org/feeds/propublica/main", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "No partidista investigativa", pais: "ESTADOS UNIDOS" },
  { id: "reforma", medio: "Reforma", url: "https://www.reforma.com/rss/portada.xml", idioma: "es", alcance: "latam", peso: 1.3, nivel: "A", eje: "Promercado / crítico del gobierno", pais: "MÉXICO" },
  { id: "reuters", medio: "Reuters", url: "https://news.google.com/rss/search?q=when:2d+site:reuters.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Occidental-global", pais: "INTERNACIONAL" },
  { id: "sbs-news", medio: "SBS News", url: "https://www.sbs.com.au/news/feed", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Australia / Asia-Pacífico", pais: "AUSTRALIA" },
  { id: "sydney-morning-herald", medio: "Sydney Morning Herald", url: "https://www.smh.com.au/rss/feed.xml", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Occidental / Australia", pais: "AUSTRALIA" },
  { id: "the-globe-and-mail", medio: "The Globe and Mail", url: "https://www.theglobeandmail.com/arc/outboundfeeds/rss/?outputType=xml", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Occidental / negocios", pais: "CANADÁ" },
  { id: "the-guardian", medio: "The Guardian", url: "https://www.theguardian.com/international/rss", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Occidental progresista", pais: "REINO UNIDO" },
  { id: "the-hindu", medio: "The Hindu", url: "https://news.google.com/rss/search?q=when:2d+site:thehindu.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "India no alineada", pais: "INDIA" },
  { id: "the-indian-express", medio: "The Indian Express", url: "https://indianexpress.com/feed", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "India plural", pais: "INDIA" },
  { id: "the-new-york-times", medio: "The New York Times", url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", idioma: "en", alcance: "global", peso: 1.3, nivel: "A", eje: "Atlántico-occidental", pais: "ESTADOS UNIDOS" },
  { id: "vlast-kz", medio: "Vlast.kz", url: "https://vlast.kz/feed/", idioma: "ru", alcance: "global", peso: 1.3, nivel: "A", eje: "Kazajistán pluralista", pais: "KAZAJISTÁN" },
  { id: "14ymedio", medio: "14ymedio", url: "https://www.14ymedio.com/rss/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Anti-gobierno cubano", pais: "CUBA/EXILIO" },
  { id: "abc", medio: "ABC", url: "https://www.abc.es/rss/2.0/portada/", idioma: "es", alcance: "global", peso: 1, nivel: "B", eje: "Atlántico-conservador", pais: "ESPAÑA" },
  { id: "africanews", medio: "Africanews", url: "https://www.africanews.com/feed", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Regional africano", pais: "PANAFRICANO" },
  { id: "agerpres", medio: "Agerpres", url: "https://agerpres.ro/english/rss/", idioma: "ro", alcance: "global", peso: 1, nivel: "B", eje: "Rumania / UE", pais: "RUMANIA" },
  { id: "al-jazeera-english", medio: "Al Jazeera English", url: "https://www.aljazeera.com/xml/rss/all.xml", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Qatar / no alineamiento pragmático", pais: "QATAR/REGIONAL" },
  { id: "al-monitor", medio: "Al-Monitor", url: "https://www.al-monitor.com/rss", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Pragmático / Washington-regional", pais: "REGIONAL" },
  { id: "ambito-financiero", medio: "Ámbito Financiero", url: "https://news.google.com/rss/search?q=when:2d+site:ambito.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Regional / mercado", pais: "ARGENTINA" },
  { id: "anadolu-agency", medio: "Anadolu Agency", url: "https://www.aa.com.tr/en/rss", idioma: "tr", alcance: "global", peso: 1, nivel: "B", eje: "Turquía / autonomía estratégica", pais: "TURQUÍA/INTERNACIONAL" },
  { id: "arise-news", medio: "Arise News", url: "https://www.arise.tv/rss", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Nigeria / África global", pais: "NIGERIA" },
  { id: "biobiochile", medio: "BioBioChile", url: "https://feeds.feedburner.com/radiobiobio/NNeJ", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Chile regional", pais: "CHILE" },
  { id: "buenos-aires-herald", medio: "Buenos Aires Herald", url: "https://buenosairesherald.com/feed", idioma: "en", alcance: "ar", peso: 1, nivel: "B", eje: "Argentina internacional", pais: "ARGENTINA" },
  { id: "caracol-radio", medio: "Caracol Radio", url: "https://caracol.com.co/arc/outboundfeeds/rss/?outputType=xml", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Iberoamericano / institucional", pais: "COLOMBIA" },
  { id: "clarin", medio: "Clarín", url: "https://www.clarin.com/rss", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Prooccidental / mercado", pais: "ARGENTINA" },
  { id: "cnn", medio: "CNN", url: "https://news.google.com/rss/search?q=when:2d+site:cnn.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Atlántico-occidental", pais: "ESTADOS UNIDOS" },
  { id: "contralinea", medio: "Contralínea", url: "https://contralinea.com.mx/feed/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Antiintervencionista", pais: "MÉXICO" },
  { id: "crikey", medio: "Crikey", url: "https://www.crikey.com.au/feed/", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Crítico del poder", pais: "AUSTRALIA" },
  { id: "daily-trust", medio: "Daily Trust", url: "https://dailytrust.com/rss", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Nigeria regional", pais: "NIGERIA" },
  { id: "democracy-now", medio: "Democracy Now!", url: "https://news.google.com/rss/search?q=when:2d+site:democracynow.org&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Antiimperialista", pais: "ESTADOS UNIDOS" },
  { id: "digi24", medio: "Digi24", url: "https://www.digi24.ro/rss", idioma: "ro", alcance: "global", peso: 1, nivel: "B", eje: "Atlántico / UE", pais: "RUMANIA" },
  { id: "el-ciudadano", medio: "El Ciudadano", url: "https://www.elciudadano.com/feed/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Antiimperialista / soberanista", pais: "CHILE" },
  { id: "el-comercio", medio: "El Comercio", url: "https://elcomercio.pe/arcio/rss/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Promercado", pais: "PERÚ" },
  { id: "el-deber", medio: "El Deber", url: "https://eldeber.com.bo/feed", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Oriente / promecado", pais: "BOLIVIA" },
  { id: "el-espanol", medio: "El Español", url: "https://www.elespanol.com/rss/", idioma: "es", alcance: "global", peso: 1, nivel: "B", eje: "Occidental / europeísta", pais: "ESPAÑA" },
  { id: "el-grito-del-sur", medio: "El Grito del Sur", url: "https://elgritodelsur.com.ar/feed/", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Latinoamericanista / soberanista", pais: "ARGENTINA" },
  { id: "el-universal", medio: "El Universal", url: "https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "México institucional", pais: "MÉXICO" },
  { id: "euronews", medio: "Euronews", url: "https://www.euronews.com/rss", idioma: "multilingüe", alcance: "global", peso: 1, nivel: "B", eje: "Europeísta", pais: "UNIÓN EUROPEA" },
  { id: "hotnews", medio: "HotNews", url: "https://hotnews.ro/rss", idioma: "ro", alcance: "global", peso: 1, nivel: "B", eje: "Atlántico / UE", pais: "RUMANIA" },
  { id: "ikon-mn", medio: "iKon.mn", url: "https://ikon.mn/rss", idioma: "mn", alcance: "global", peso: 1, nivel: "B", eje: "Mongolia urbana", pais: "MONGOLIA" },
  { id: "il-manifesto", medio: "Il Manifesto", url: "https://ilmanifesto.it/rss", idioma: "it", alcance: "global", peso: 1, nivel: "B", eje: "Antiimperialista", pais: "ITALIA" },
  { id: "infobae", medio: "Infobae", url: "https://www.infobae.com/arc/outboundfeeds/rss/argentina/", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Prooccidental", pais: "ARGENTINA" },
  { id: "kan-news", medio: "KAN News", url: "https://www.kan.org.il/api/newsflash/v2/Newsflash", idioma: "he", alcance: "global", peso: 1, nivel: "B", eje: "Israel estatal/público", pais: "ISRAEL" },
  { id: "kommersant", medio: "Kommersant", url: "https://news.google.com/rss/search?q=when:2d+site:kommersant.ru&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "ru", alcance: "global", peso: 1, nivel: "B", eje: "Rusia institucional", pais: "RUSIA" },
  { id: "la-razon", medio: "La Razón", url: "https://larazon.bo/feed/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Bolivia nacional-popular", pais: "BOLIVIA" },
  { id: "la-republica", medio: "La República", url: "https://larepublica.pe/rss.xml", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Perú progresista", pais: "PERÚ" },
  { id: "le-figaro", medio: "Le Figaro", url: "https://news.google.com/rss/search?q=when:2d+site:lefigaro.fr&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "fr", alcance: "global", peso: 1, nivel: "B", eje: "Europeísta-conservador", pais: "FRANCIA" },
  { id: "medyascope", medio: "Medyascope", url: "https://medyascope.tv/feed/", idioma: "tr", alcance: "global", peso: 1, nivel: "B", eje: "Pluralista", pais: "TURQUÍA" },
  { id: "mongolian-national-broadcast", medio: "Mongolian National Broadcaster (MNB)", url: "https://www.mnb.mn/rss", idioma: "mn", alcance: "global", peso: 1, nivel: "B", eje: "Mongolia nacional", pais: "MONGOLIA" },
  { id: "national-post", medio: "National Post", url: "https://nationalpost.com/rss", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Occidental-conservador", pais: "CANADÁ" },
  { id: "nodal-infonodal", medio: "NODAL / InfoNODAL", url: "https://www.nodal.am/feed/", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Antiimperialista / integración regional", pais: "ARGENTINA/REGIONAL" },
  { id: "noticias-argentinas", medio: "Noticias Argentinas", url: "https://noticiasargentinas.com/rss", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Argentina mainstream", pais: "ARGENTINA" },
  { id: "o-globo", medio: "O Globo", url: "https://oglobo.globo.com/rss/oglobo", idioma: "pt", alcance: "latam", peso: 1, nivel: "B", eje: "Prooccidental / mercado", pais: "BRASIL" },
  { id: "oncuba", medio: "OnCuba", url: "https://oncubanews.com/feed/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Puente Cuba-diáspora", pais: "CUBA" },
  { id: "orda-kz", medio: "Orda.kz", url: "https://orda.kz/feed/", idioma: "ru", alcance: "global", peso: 1, nivel: "B", eje: "Kazajistán pluralista", pais: "KAZAJISTÁN" },
  { id: "pagina-12", medio: "Página/12", url: "https://www.pagina12.com.ar/arc/outboundfeeds/rss/?outputType=xml", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Latinoamericanista / anti-neoliberal", pais: "ARGENTINA" },
  { id: "perfil", medio: "Perfil", url: "https://www.perfil.com/feed", idioma: "es", alcance: "ar", peso: 1, nivel: "B", eje: "Argentina plural", pais: "ARGENTINA" },
  { id: "politico", medio: "Politico", url: "https://www.politico.com/rss/politicopicks.xml", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Atlántico-occidental", pais: "ESTADOS UNIDOS" },
  { id: "politico-europe", medio: "Politico Europe", url: "https://www.politico.eu/feed/", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Atlántico / UE", pais: "UNIÓN EUROPEA" },
  { id: "publico", medio: "Público", url: "https://news.google.com/rss/search?q=when:2d+site:publico.es&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "global", peso: 1, nivel: "B", eje: "Antiintervencionista / progresista", pais: "ESPAÑA" },
  { id: "reason", medio: "Reason", url: "https://reason.com/feed/", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "No intervencionista / mercado", pais: "ESTADOS UNIDOS" },
  { id: "rompeviento-tv", medio: "Rompeviento TV", url: "https://www.rompeviento.tv/feed/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Anti-neoliberal", pais: "MÉXICO" },
  { id: "rtve-noticias", medio: "RTVE Noticias", url: "https://news.google.com/rss/search?q=when:2d+site:rtve.es&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "global", peso: 1, nivel: "B", eje: "España / UE", pais: "ESPAÑA" },
  { id: "sabc-news", medio: "SABC News", url: "https://www.sabcnews.com/sabcnews/feed/", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Sudáfrica estatal/público", pais: "SUDÁFRICA" },
  { id: "scroll-in", medio: "Scroll.in", url: "https://feeds.feedburner.com/ScrollinArticles.rss", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "India pluralista", pais: "INDIA" },
  { id: "sixth-tone", medio: "Sixth Tone", url: "http://www.sixthtone.com/rss/index.xml", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "China urbana", pais: "CHINA" },
  { id: "south-china-morning-post", medio: "South China Morning Post", url: "https://www.scmp.com/rss/feed", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "China/Hong Kong global", pais: "HONG KONG" },
  { id: "talcual", medio: "TalCual", url: "https://talcualdigital.com/feed/", idioma: "es", alcance: "latam", peso: 1, nivel: "B", eje: "Anti-gobierno", pais: "VENEZUELA" },
  { id: "taz", medio: "taz", url: "https://taz.de/rss.xml", idioma: "de", alcance: "global", peso: 1, nivel: "B", eje: "Crítica occidental", pais: "ALEMANIA" },
  { id: "the-express-tribune", medio: "The Express Tribune", url: "https://tribune.com.pk/en/feed", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Pakistán global", pais: "PAKISTÁN" },
  { id: "the-intercept", medio: "The Intercept", url: "https://theintercept.com/rss", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Antiintervencionista", pais: "ESTADOS UNIDOS" },
  { id: "the-japan-times", medio: "The Japan Times", url: "https://www.japantimes.co.jp/feed/", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Japón internacional", pais: "JAPÓN" },
  { id: "the-times-of-israel", medio: "The Times of Israel", url: "https://www.timesofisrael.com/feed/", idioma: "en", alcance: "global", peso: 1, nivel: "B", eje: "Pro-Israel moderado", pais: "ISRAEL" },
  { id: "tv-brasil", medio: "TV Brasil", url: "https://tvbrasil.ebc.com.br/rss.xml", idioma: "pt", alcance: "latam", peso: 1, nivel: "B", eje: "Brasil estatal/público", pais: "BRASIL" },
  { id: "agencia-andina", medio: "Agencia Andina", url: "https://andina.pe/agencia/rss", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Perú estatal", pais: "PERÚ" },
  { id: "arab-news", medio: "Arab News", url: "https://www.arabnews.com/rss.xml", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Arabia Saudita / occidental", pais: "ARABIA SAUDITA" },
  { id: "ary-news", medio: "ARY News", url: "https://arynews.tv/feed", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Pakistán nacional", pais: "PAKISTÁN" },
  { id: "associated-press-of-pakistan", medio: "Associated Press of Pakistan", url: "https://www.app.com.pk/rss", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Pakistán / gobierno", pais: "PAKISTÁN" },
  { id: "bild", medio: "Bild", url: "http://www.bild.de/rss-feeds/rss-16725492,feed=home.bild.html", idioma: "de", alcance: "global", peso: 0.6, nivel: "C", eje: "Atlántico / pro-Israel declarado", pais: "ALEMANIA" },
  { id: "brasil-de-fato", medio: "Brasil de Fato", url: "https://www.brasildefato.com.br/feed/", idioma: "pt", alcance: "latam", peso: 0.6, nivel: "C", eje: "Antiimperialista", pais: "BRASIL" },
  { id: "cgtn", medio: "CGTN", url: "https://news.google.com/rss/search?q=when:2d+site:cgtn.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "zh", alcance: "global", peso: 0.6, nivel: "C", eje: "China / multipolar estatal", pais: "CHINA" },
  { id: "china-news-service-ecns", medio: "China News Service / ECNS", url: "https://www.ecns.cn/rss.xml", idioma: "zh", alcance: "global", peso: 0.6, nivel: "C", eje: "China / diáspora y proyección internacional", pais: "CHINA" },
  { id: "daily-sabah", medio: "Daily Sabah", url: "https://www.dailysabah.com/rss/all.xml", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Turquía / Erdoğan", pais: "TURQUÍA" },
  { id: "diario-de-cuba", medio: "Diario de Cuba", url: "https://diariodecuba.com/rss.xml", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Anti-gobierno cubano", pais: "CUBA/EXILIO" },
  { id: "fox-news", medio: "Fox News", url: "https://moxie.foxnews.com/google-publisher/latest.xml", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Nacional-conservador / pro-EE.UU.", pais: "ESTADOS UNIDOS" },
  { id: "globovision", medio: "Globovisión", url: "https://www.globovision.com/rss.xml", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Venezuela institucional", pais: "VENEZUELA" },
  { id: "il-giornale", medio: "Il Giornale", url: "https://www.ilgiornale.it/arc/outboundfeeds/rss/?outputType=xml", idioma: "it", alcance: "global", peso: 0.6, nivel: "C", eje: "Nacional-conservador", pais: "ITALIA" },
  { id: "irna", medio: "IRNA", url: "https://en.irna.ir/rss", idioma: "fa", alcance: "global", peso: 0.6, nivel: "C", eje: "Irán / antihegemonía occidental", pais: "IRÁN/INTERNACIONAL" },
  { id: "jewish-news-syndicate-jns", medio: "Jewish News Syndicate (JNS)", url: "https://www.jns.org/index.rss", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Sionista conservador", pais: "ESTADOS UNIDOS/ISRAEL" },
  { id: "jovem-pan", medio: "Jovem Pan", url: "https://jovempan.com.br/rss", idioma: "pt", alcance: "latam", peso: 0.6, nivel: "C", eje: "Conservador / pro-EE.UU.", pais: "BRASIL" },
  { id: "kenya-broadcasting-corporati", medio: "Kenya Broadcasting Corporation (KBC)", url: "https://www.kbc.co.ke/rss", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Kenia estatal", pais: "KENIA" },
  { id: "la-izquierda-diario", medio: "La Izquierda Diario", url: "https://news.google.com/rss/search?q=when:2d+site:laizquierdadiario.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "ar", peso: 0.6, nivel: "C", eje: "Antiimperialista", pais: "ARGENTINA" },
  { id: "la-patilla", medio: "La Patilla", url: "https://lapatilla.com/feed/", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Anti-chavista / prooccidental", pais: "VENEZUELA" },
  { id: "map", medio: "MAP", url: "https://news.google.com/rss/search?q=when:2d+site:mapnews.ma&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "ar", alcance: "global", peso: 0.6, nivel: "C", eje: "Marruecos / monarquía", pais: "MARRUECOS" },
  { id: "mehr-news-agency", medio: "Mehr News Agency", url: "https://en.mehrnews.com/rss", idioma: "fa", alcance: "global", peso: 0.6, nivel: "C", eje: "Irán / República Islámica", pais: "IRÁN" },
  { id: "middle-east-eye", medio: "Middle East Eye", url: "https://www.middleeasteye.net/rss", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Afinidad catarí alegada", pais: "REINO UNIDO/REGIONAL" },
  { id: "mondoweiss", medio: "Mondoweiss", url: "https://mondoweiss.net/feed/", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Antisionista / antiocupación", pais: "ESTADOS UNIDOS/PALESTINA" },
  { id: "national-review", medio: "National Review", url: "https://www.nationalreview.com/feed/", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Conservador estadounidense", pais: "ESTADOS UNIDOS" },
  { id: "prensa-latina", medio: "Prensa Latina", url: "https://www.prensa-latina.cu/feed/", idioma: "es", alcance: "global", peso: 0.6, nivel: "C", eje: "Cuba / antiimperialista", pais: "CUBA/INTERNACIONAL" },
  { id: "qazinform", medio: "Qazinform", url: "https://qazinform.com/feed.xml", idioma: "kk", alcance: "global", peso: 0.6, nivel: "C", eje: "Kazajistán / multivectorial", pais: "KAZAJISTÁN" },
  { id: "rtvc-noticias", medio: "RTVC Noticias", url: "https://www.rtvcnoticias.com/rss.xml", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Colombia estatal", pais: "COLOMBIA" },
  { id: "semana", medio: "Semana", url: "https://www.semana.com/arc/outboundfeeds/rss/?outputType=xml", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Prooccidental / conservador", pais: "COLOMBIA" },
  { id: "tehran-times", medio: "Tehran Times", url: "https://www.tehrantimes.com/rss", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Irán estatal", pais: "IRÁN" },
  { id: "the-astana-times", medio: "The Astana Times", url: "https://astanatimes.com/feed/", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Kazajistán internacional", pais: "KAZAJISTÁN" },
  { id: "the-electronic-intifada", medio: "The Electronic Intifada", url: "https://electronicintifada.net/rss.xml", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Antiocupación", pais: "ESTADOS UNIDOS/PALESTINA" },
  { id: "trt-world", medio: "TRT World", url: "https://www.trtworld.com/feed/rss.xml", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Turquía / autonomía estratégica", pais: "TURQUÍA" },
  { id: "ultimas-noticias", medio: "Últimas Noticias", url: "https://ultimasnoticias.com.ve/feed/", idioma: "es", alcance: "latam", peso: 0.6, nivel: "C", eje: "Bolivariano", pais: "VENEZUELA" },
  { id: "voice-of-america-voa", medio: "Voice of America (VOA)", url: "https://www.voanews.com/api/", idioma: "en", alcance: "global", peso: 0.6, nivel: "C", eje: "Proyección exterior estadounidense", pais: "ESTADOS UNIDOS" },
  { id: "wafa", medio: "WAFA", url: "https://news.google.com/rss/search?q=when:2d+site:english.wafa.ps&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "ar", alcance: "global", peso: 0.6, nivel: "C", eje: "Pro-Palestina / AP", pais: "PALESTINA" },
  { id: "xinhua", medio: "Xinhua", url: "https://news.google.com/rss/search?q=when:2d+site:news.cn&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "zh", alcance: "global", peso: 0.6, nivel: "C", eje: "China / multipolar estatal", pais: "CHINA/INTERNACIONAL" },
  { id: "al-mayadeen", medio: "Al Mayadeen", url: "https://news.google.com/rss/search?q=when:2d+site:almayadeen.net&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "ar", alcance: "global", peso: 0.3, nivel: "D", eje: "Antiimperialista / pro-Irán", pais: "LÍBANO/REGIONAL" },
  { id: "cubadebate", medio: "Cubadebate", url: "http://www.cubadebate.cu/feed/", idioma: "es", alcance: "latam", peso: 0.3, nivel: "D", eje: "Cuba / antiimperialista", pais: "CUBA" },
  { id: "global-times", medio: "Global Times", url: "https://news.google.com/rss/search?q=when:2d+site:globaltimes.cn&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "zh", alcance: "global", peso: 0.3, nivel: "D", eje: "China / nacionalismo", pais: "CHINA" },
  { id: "hispantv", medio: "HispanTV", url: "https://news.google.com/rss/search?q=when:2d+site:hispantv.com&hl=es-419&gl=AR&ceid=AR:es-419", idioma: "es", alcance: "global", peso: 0.3, nivel: "D", eje: "Irán / antiimperialista", pais: "IRÁN" },
  { id: "kayhan", medio: "Kayhan", url: "https://kayhan.ir/en/rss/allnews", idioma: "fa", alcance: "global", peso: 0.3, nivel: "D", eje: "Irán / liderazgo religioso", pais: "IRÁN" },
  { id: "la-derecha-diario", medio: "La Derecha Diario", url: "https://derechadiario.com.ar/rss", idioma: "es", alcance: "ar", peso: 0.3, nivel: "D", eje: "Prooccidental / libertario", pais: "ARGENTINA" },
  { id: "rt", medio: "RT", url: "https://www.rt.com/rss", idioma: "multilingüe", alcance: "global", peso: 0.3, nivel: "D", eje: "Rusia / antihegemonía occidental", pais: "RUSIA" },
  { id: "sputnik", medio: "Sputnik", url: "https://sputnikglobe.com/export/rss2/archive/index.xml", idioma: "multilingüe", alcance: "global", peso: 0.3, nivel: "D", eje: "Rusia / antihegemonía occidental", pais: "RUSIA" },
  { id: "telesur", medio: "Telesur", url: "https://www.telesurtv.net/feed/", idioma: "es", alcance: "latam", peso: 0.3, nivel: "D", eje: "Bolivariano / antiimperialista", pais: "VENEZUELA" },
];

export const porId = (id) => FUENTES.find((f) => f.id === id);

/** Los que sirven para dar por confirmado un hecho. */
export const DE_VERIFICACION = FUENTES.filter((f) => f.nivel === 'A' || f.nivel === 'B');

/** Un hecho sostenido solo por estos no se publica como confirmado. */
export const SOLO_MONITOREO = FUENTES.filter((f) => f.nivel === 'D');
